site_name: Esmerald Sessions
site_description: The scheduler that nobody wanted but the one that every application needs.
site_url: https://esmerald-sessions.dymmond.com

theme:
  name: "material"
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: "default"
      primary: "pink"
      accent: "red"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/toggle-switch-variant"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "pink"
      accent: "red"
      toggle:
        icon: "material/toggle-switch-variant-off"
        name: "Switch to light mode"
  favicon: statics/images/favicon.ico
  logo: statics/images/logo-white.svg
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

repo_name: dymmond/esmerald-sessions
repo_url: https://github.com/dymmond/esmerald-sessions
edit_uri: ""
plugins:
  - search
  - markdownextradata:
      data: data

nav:
  - Esmerald Sessions: "index.md"
  - Usage: "usage.md"
  - Contributing: "contributing.md"
  - Sponsorship: "sponsorship.md"
  - Release Notes: "release-notes.md"
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  alternate:
    - link: /
      name: English
      lang: en
    # - link: /pt/
    #   name: Portuguese (Portugal)
    #   lang: en

extra_css:
  - statics/css/custom.css
